Add remove
sumairq/Todo-List-Microverse pull request #3
Opened 2022-01-28 20:53 UTC by sumairq

## Added the following functionality

- Create tasks
- Delete tasks
- Edit Tasks

2022-01-28 21:32 UTC, hiromataba requested changes
Hi :wave:  @sumairq , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
### To highlight :champagne: 
- Descriptive README file :heavy_check_mark: 
- Your linters are passing :+1: 

## Required Changes ♻️

- [ ] Since you are working with webpack, I think it would be better to add the commands in your README file to install npm `npm install` and to start the server `npm start``

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-28 21:32 UTC, hiromataba commented on src/modules/todoCollection.js
> +    this.setStorage();
- [ ] Please use normal functions for this project as mentioned in the project requirement, not classes, Kindly replace your classes with functions and follow the project requirement to implement the required functionalities 

![image](https://user-images.githubusercontent.com/75126481/151623767-4871c551-57f5-4617-9043-9116464e5bda.png)

2022-01-28 21:32 UTC, hiromataba commented on src/modules/item.js
> +}
- [ ] Please use normal functions for this project as mentioned in the project requirement, not classes, Kindly replace your classes with functions and follow the project requirement to implement the required functionalities 

![image](https://user-images.githubusercontent.com/75126481/151623767-4871c551-57f5-4617-9043-9116464e5bda.png)

2022-01-29 05:39 UTC, ShoiraTa commented
### **STATUS: APPROVED  ✔️** 
------
Hi @sumairq ,  

Your project is complete! Congratulations!  🎉💯🌟 
Everything is up and running!

<img src="https://www.serialminds.com/wp-content/uploads/2015/11/loser.gif" width="400" height="250" />

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-29 05:42 UTC, merged